'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { useState } from 'react';
import { Menu, X, ChevronDown, MapPin, Phone } from 'lucide-react';
export default function Header() {
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    const [destinationsOpen, setDestinationsOpen] = useState(false);
    const navItems = [
        { name: 'Home', href: '/' },
        { name: 'About', href: '/about' },
        {
            name: 'Destinations',
            href: '#',
            dropdown: true,
            items: [
                { name: 'North India', href: '/destinations/north', description: 'Delhi, Rajasthan, Himachal & more' },
                { name: 'South India', href: '/destinations/south', description: 'Kerala, Tamil Nadu, Karnataka & more' },
                { name: 'East India', href: '/destinations/east', description: 'West Bengal, Odisha & more' },
                { name: 'West India', href: '/destinations/west', description: 'Gujarat, Maharashtra & more' },
                { name: 'Central India', href: '/destinations/central', description: 'Madhya Pradesh & Chhattisgarh' },
                { name: 'Northeast India', href: '/destinations/northeast', description: 'Seven Sisters & Sikkim' },
            ]
        },
        { name: 'Packages', href: '/packages' },
        { name: 'Services', href: '/services' },
        { name: 'Contact', href: '/contact' },
    ];
    return (_jsxs("header", { className: "fixed top-0 left-0 right-0 z-50 bg-[#0A0A0A]/95 backdrop-blur-md border-b border-[#C9A96E]/20", children: [_jsx("div", { className: "hidden lg:block border-b border-[#C9A96E]/10 bg-[#0A0A0A]", children: _jsxs("div", { className: "max-w-7xl mx-auto px-6 py-2 flex justify-between items-center text-xs", children: [_jsxs("div", { className: "flex items-center gap-6 text-[#888]", children: [_jsxs("span", { className: "flex items-center gap-2", children: [_jsx(MapPin, { className: "w-3 h-3 text-[#C9A96E]" }), "New Delhi, India"] }), _jsxs("span", { className: "flex items-center gap-2", children: [_jsx(Phone, { className: "w-3 h-3 text-[#C9A96E]" }), "+91 98765 43210"] })] }), _jsxs("div", { className: "flex items-center gap-4 text-[#888]", children: [_jsx("span", { children: "Follow us:" }), _jsxs("div", { className: "flex gap-3", children: [_jsx("a", { href: "https://instagram.com", target: "_blank", rel: "noopener noreferrer", className: "hover:text-[#C9A96E] transition-colors", children: "Instagram" }), _jsx("a", { href: "https://facebook.com", target: "_blank", rel: "noopener noreferrer", className: "hover:text-[#C9A96E] transition-colors", children: "Facebook" }), _jsx("a", { href: "https://x.com", target: "_blank", rel: "noopener noreferrer", className: "hover:text-[#C9A96E] transition-colors", children: "Twitter" })] })] })] }) }), _jsx("div", { className: "max-w-7xl mx-auto px-6 py-4", children: _jsxs("div", { className: "flex justify-between items-center", children: [_jsxs(Link, { to: "/", className: "flex items-center gap-3 group", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-[#C9A96E] flex items-center justify-center", children: _jsx("span", { className: "text-[#0A0A0A] font-serif font-bold text-lg", children: "V" }) }), _jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-xl font-serif font-bold text-white group-hover:text-[#C9A96E] transition-colors", children: "Vacation Clock" }), _jsx("span", { className: "text-[10px] uppercase tracking-[0.2em] text-[#888]", children: "Premium Travel" })] })] }), _jsx("nav", { className: "hidden lg:flex items-center gap-1", children: navItems.map((item) => {
                                var _a;
                                return (_jsxs("div", { className: "relative group", children: [item.dropdown ? (_jsxs("button", { className: "flex items-center gap-1 px-4 py-2 text-sm font-medium text-[#ccc] hover:text-[#C9A96E] transition-colors uppercase tracking-wider", onMouseEnter: () => setDestinationsOpen(true), onMouseLeave: () => setDestinationsOpen(false), children: [item.name, _jsx(ChevronDown, { className: "w-4 h-4 transition-transform group-hover:rotate-180" })] })) : (_jsx(Link, { to: item.href, className: "px-4 py-2 text-sm font-medium text-[#ccc] hover:text-[#C9A96E] transition-colors uppercase tracking-wider", children: item.name })), item.dropdown && (_jsxs("div", { className: `absolute top-full left-0 w-72 bg-[#141414] border border-[#C9A96E]/20 rounded-lg shadow-2xl transition-all duration-300 ${destinationsOpen ? 'opacity-100 visible translate-y-0' : 'opacity-0 invisible -translate-y-2'}`, onMouseEnter: () => setDestinationsOpen(true), onMouseLeave: () => setDestinationsOpen(false), children: [_jsx("div", { className: "p-2", children: (_a = item.items) === null || _a === void 0 ? void 0 : _a.map((subItem) => (_jsxs(Link, { to: subItem.href, className: "block px-4 py-3 rounded-md hover:bg-[#C9A96E]/10 transition-colors group/item", children: [_jsx("span", { className: "block text-sm font-medium text-white group-hover/item:text-[#C9A96E] transition-colors", children: subItem.name }), _jsx("span", { className: "block text-xs text-[#888] mt-0.5", children: subItem.description })] }, subItem.name))) }), _jsx("div", { className: "border-t border-[#C9A96E]/10 p-4", children: _jsxs(Link, { to: "/destinations", className: "text-xs uppercase tracking-wider text-[#C9A96E] hover:text-[#E8D5B5] transition-colors flex items-center gap-2", children: ["View All Destinations", _jsx("span", { className: "text-lg", children: "\u2192" })] }) })] }))] }, item.name));
                            }) }), _jsx("div", { className: "hidden lg:flex items-center gap-4", children: _jsx(Link, { to: "/booking", className: "px-6 py-2.5 bg-[#C9A96E] text-[#0A0A0A] text-sm font-semibold rounded-lg hover:bg-[#E8D5B5] transition-all duration-300 uppercase tracking-wider", children: "Book Now" }) }), _jsx("button", { className: "lg:hidden p-2 text-white", onClick: () => setMobileMenuOpen(!mobileMenuOpen), children: mobileMenuOpen ? _jsx(X, { className: "w-6 h-6" }) : _jsx(Menu, { className: "w-6 h-6" }) })] }) }), _jsx("div", { className: `lg:hidden absolute top-full left-0 right-0 bg-[#0A0A0A] border-b border-[#C9A96E]/20 transition-all duration-300 ${mobileMenuOpen ? 'opacity-100 visible' : 'opacity-0 invisible'}`, children: _jsxs("nav", { className: "max-w-7xl mx-auto px-6 py-4 space-y-2", children: [navItems.map((item) => {
                            var _a;
                            return (_jsx("div", { children: item.dropdown ? (_jsxs("div", { children: [_jsxs("button", { className: "w-full flex items-center justify-between py-3 text-[#ccc] hover:text-[#C9A96E] transition-colors", onClick: () => setDestinationsOpen(!destinationsOpen), children: [_jsx("span", { className: "uppercase tracking-wider text-sm font-medium", children: item.name }), _jsx(ChevronDown, { className: `w-4 h-4 transition-transform ${destinationsOpen ? 'rotate-180' : ''}` })] }), destinationsOpen && (_jsx("div", { className: "pl-4 space-y-2 pb-2", children: (_a = item.items) === null || _a === void 0 ? void 0 : _a.map((subItem) => (_jsx(Link, { to: subItem.href, className: "block py-2 text-sm text-[#888] hover:text-[#C9A96E] transition-colors", onClick: () => setMobileMenuOpen(false), children: subItem.name }, subItem.name))) }))] })) : (_jsx(Link, { to: item.href, className: "block py-3 text-[#ccc] hover:text-[#C9A96E] transition-colors uppercase tracking-wider text-sm font-medium", onClick: () => setMobileMenuOpen(false), children: item.name })) }, item.name));
                        }), _jsx("div", { className: "pt-4 border-t border-[#C9A96E]/10", children: _jsx(Link, { to: "/booking", className: "block w-full text-center px-6 py-3 bg-[#C9A96E] text-[#0A0A0A] font-semibold rounded-lg uppercase tracking-wider text-sm", onClick: () => setMobileMenuOpen(false), children: "Book Now" }) })] }) })] }));
}
