import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import Header from '@/components/tourism/Header';
import Footer from '@/components/tourism/Footer';
import statesData from '@/public/data/states.json';
import { ArrowRight, Clock, MapPin, Users } from 'lucide-react';
export default function PackagesPage() {
    const states = statesData.regions.flatMap((region) => region.states);
    const packages = states
        .flatMap((state) => (state.packages || []).map((pkg) => (Object.assign(Object.assign({}, pkg), { stateId: state.id, stateName: state.name, region: state.region }))))
        .sort((a, b) => a.price - b.price);
    return (_jsxs("main", { className: "min-h-screen bg-background", children: [_jsx(Header, {}), _jsx("section", { className: "pt-32 pb-14 bg-[#0A0A0A]", children: _jsxs("div", { className: "max-w-7xl mx-auto px-6", children: [_jsxs("h1", { className: "text-4xl md:text-5xl font-serif font-bold text-white mb-4", children: ["Curated Travel ", _jsx("span", { className: "text-[#C9A96E]", children: "Packages" })] }), _jsx("p", { className: "text-[#888] max-w-3xl text-lg", children: "Compare ready-to-book journeys across India. Every package can be customized with your preferred dates and experiences." })] }) }), _jsx("section", { className: "py-16 bg-[#141414]", children: _jsx("div", { className: "max-w-7xl mx-auto px-6", children: _jsx("div", { className: "grid md:grid-cols-2 lg:grid-cols-3 gap-6", children: packages.map((pkg) => (_jsxs("article", { className: "rounded-2xl border border-[#C9A96E]/20 bg-[#1A1A1A] p-6 hover:border-[#C9A96E]/40 transition-colors", children: [_jsx("div", { className: "mb-4", children: _jsxs("span", { className: "inline-flex px-3 py-1 rounded-full text-xs font-semibold bg-[#C9A96E]/15 text-[#C9A96E]", children: [pkg.region, " India"] }) }), _jsx("h2", { className: "text-2xl font-serif font-bold text-white mb-2", children: pkg.name }), _jsxs("p", { className: "text-sm text-[#888] flex items-center gap-2 mb-4", children: [_jsx(MapPin, { className: "w-4 h-4" }), pkg.stateName] }), _jsxs("div", { className: "space-y-3 mb-5", children: [_jsxs("p", { className: "text-sm text-[#aaa] flex items-center gap-2", children: [_jsx(Clock, { className: "w-4 h-4 text-[#C9A96E]" }), pkg.duration] }), _jsxs("p", { className: "text-sm text-[#aaa] flex items-center gap-2", children: [_jsx(Users, { className: "w-4 h-4 text-[#C9A96E]" }), "Ideal for 2+ travelers"] })] }), _jsx("div", { className: "flex flex-wrap gap-2 mb-6", children: pkg.highlights.slice(0, 3).map((highlight) => (_jsx("span", { className: "text-xs px-2 py-1 rounded bg-[#C9A96E]/12 text-[#E8D5B5]", children: highlight }, highlight))) }), _jsx("div", { className: "flex items-center justify-between mb-5", children: _jsxs("div", { children: [_jsx("p", { className: "text-xs text-[#888]", children: "Starting from" }), _jsxs("p", { className: "text-2xl font-bold text-[#C9A96E]", children: ["\u20B9", pkg.price.toLocaleString()] })] }) }), _jsxs("div", { className: "flex gap-3", children: [_jsx(Link, { to: `/state/${pkg.stateId}`, className: "flex-1 inline-flex justify-center items-center px-4 py-3 border border-[#C9A96E]/35 text-[#C9A96E] rounded-lg hover:bg-[#C9A96E]/10 transition-colors", children: "View State" }), _jsxs(Link, { to: "/booking", className: "flex-1 inline-flex justify-center items-center gap-2 px-4 py-3 bg-[#C9A96E] text-[#0A0A0A] font-semibold rounded-lg hover:bg-[#E8D5B5] transition-colors", children: ["Book", _jsx(ArrowRight, { className: "w-4 h-4" })] })] })] }, `${pkg.stateId}-${pkg.name}`))) }) }) }), _jsx(Footer, {})] }));
}
