const localImages = {
  rajasthan: new URL('../assets/images/images/Rajasthan.jpg', import.meta.url).href,
  kerala: new URL('../assets/images/images/kerala.jpg', import.meta.url).href,
  himachal: new URL('../assets/images/images/Himachal Pradesh.jpg', import.meta.url).href,
  goa: new URL('../assets/images/images/Goa.jpg', import.meta.url).href,
  tamilNadu: new URL('../assets/images/images/tamil nadu.jpg', import.meta.url).href,
  uttarakhand: new URL('../assets/images/images/uttarakhand.jpg', import.meta.url).href,
  haryana: new URL('../assets/images/images/haryana.jpg', import.meta.url).href,
  punjab: new URL('../assets/images/images/punjab.jpg', import.meta.url).href,
  honeymoon: new URL('../assets/images/images/honeymoon.jpg', import.meta.url).href,
  premiumResort: new URL('../assets/images/images/premium hotel resort.jpg', import.meta.url).href,
  privateTour: new URL('../assets/images/images/private tour guide.jpg', import.meta.url).href,
  itinerary: new URL('../assets/images/images/itenary.jpg', import.meta.url).href,
  adventure: new URL('../assets/images/images/advanture.jpg', import.meta.url).href,
  andhraPradesh: new URL('../assets/images/images/andhra pradesh.jpg', import.meta.url).href,
  sikkim: new URL('../assets/images/images/sikkim.jpg', import.meta.url).href,
  delhi: new URL('../assets/images/images/delhi.jpg', import.meta.url).href,
  maharashtra: new URL('../assets/images/images/maharashtra.jpg', import.meta.url).href,
  madhyaPradesh: new URL('../assets/images/images/madhya pradesh.jpg', import.meta.url).href,
  gujarat: new URL('../assets/images/images/gujarath.jpg', import.meta.url).href,
  odisha: new URL('../assets/images/images/odisha.jpg', import.meta.url).href,
  jammuAndKashmir: new URL('../assets/images/images/jammu and kashmir.jpg', import.meta.url).href,
  jharkhand: new URL('../assets/images/images/jharkhand.jpg', import.meta.url).href,
  meghalaya: new URL('../assets/images/images/meghalaya.jpg', import.meta.url).href,
  assam: new URL('../assets/images/images/assam.jpg', import.meta.url).href,
  manipur: new URL('../assets/images/images/manipur.jpg', import.meta.url).href,
  nagaland: new URL('../assets/images/images/nagaland.jpg', import.meta.url).href,
  mizoram: new URL('../assets/images/images/mizoram.jpg', import.meta.url).href,
  bihar: new URL('../assets/images/images/bihar.jpg', import.meta.url).href,
  karnataka: new URL('../assets/images/images/karnataka.jpg', import.meta.url).href,
  westBengal: new URL('../assets/images/images/west bengal.jpg', import.meta.url).href,
  arunachalPradesh: new URL('../assets/images/images/arunachal pradesh.jpg', import.meta.url).href,
  nature: new URL('../assets/images/images/nature.jpg', import.meta.url).href,
  photography: new URL('../assets/images/images/photography.jpg', import.meta.url).href,
  // Premium destinations (home page)
  manali: new URL('../assets/destinations/manali.png', import.meta.url).href,
  lehLadakh: new URL('../assets/destinations/leh ladhak.png', import.meta.url).href,
  munnar: new URL('../assets/destinations/munnar.png', import.meta.url).href,
  ooty: new URL('../assets/destinations/ooty.png', import.meta.url).href,
  darjeeling: new URL('../assets/destinations/darjeeling.png', import.meta.url).href,
  udaipur: new URL('../assets/destinations/udaipur.png', import.meta.url).href,
  shillong: new URL('../assets/destinations/shillong.png', import.meta.url).href,
  // North India destinations
  shimla: new URL('../assets/destinations/shimla.png', import.meta.url).href,
  amritsar: new URL('../assets/destinations/amritsar.png', import.meta.url).href,
  rishikesh: new URL('../assets/destinations/rishikesh.png', import.meta.url).href,
  mussoorie: new URL('../assets/destinations/mussoorie.png', import.meta.url).href,
  nainital: new URL('../assets/destinations/nainital.png', import.meta.url).href,
  dharamshala: new URL('../assets/destinations/dharamshala.png', import.meta.url).href,
  srinagar: new URL('../assets/destinations/srinagar.png', import.meta.url).href,
  auli: new URL('../assets/destinations/auli.png', import.meta.url).href,
  // South India destinations
  alleppey: new URL('../assets/destinations/alleppey.png', import.meta.url).href,
  coorg: new URL('../assets/destinations/coorg.png', import.meta.url).href,
  hampi: new URL('../assets/destinations/hampi.png', import.meta.url).href,
  kodaikanal: new URL('../assets/destinations/kodaikanel.png', import.meta.url).href,
  wayanad: new URL('../assets/destinations/wayanad.png', import.meta.url).href,
  pondicherry: new URL('../assets/destinations/pondicherry.png', import.meta.url).href,
  gokarna: new URL('../assets/destinations/gokarna.png', import.meta.url).href,
  mysore: new URL('../assets/destinations/mysore.png', import.meta.url).href,
  // East India destinations
  gangtok: new URL('../assets/destinations/gangtok.png', import.meta.url).href,
  puri: new URL('../assets/destinations/puri.png', import.meta.url).href,
  konark: new URL('../assets/destinations/konark.png', import.meta.url).href,
  sundarbans: new URL('../assets/destinations/sundarbans.png', import.meta.url).href,
  kalimpong: new URL('../assets/destinations/kalimpong.png', import.meta.url).href,
  digha: new URL('../assets/destinations/digha.png', import.meta.url).href,
  shantiniketan: new URL('../assets/destinations/shantiniketan.png', import.meta.url).href,
  // West India destinations
  jaisalmer: new URL('../assets/destinations/jaisalmer.png', import.meta.url).href,
  mountAbu: new URL('../assets/destinations/mount abu.png', import.meta.url).href,
  kutch: new URL('../assets/destinations/kutch.png', import.meta.url).href,
  mumbai: new URL('../assets/destinations/mumbai.png', import.meta.url).href,
  alibaug: new URL('../assets/destinations/alibaug.png', import.meta.url).href,
  ajantaEllora: new URL('../assets/destinations/ajanta ellora.png', import.meta.url).href,
  // Central India destinations
  khajuraho: new URL('../assets/destinations/khajuraho.png', import.meta.url).href,
  pachmarhi: new URL('../assets/destinations/pachmari.png', import.meta.url).href,
  kanhanationalpark: new URL('../assets/destinations/kanha national park.png', import.meta.url).href,
  bhimbetka: new URL('../assets/destinations/bhimbetka.png', import.meta.url).href,
  orchha: new URL('../assets/destinations/orchha.png', import.meta.url).href,
  penchationalpark: new URL('../assets/destinations/pench national park.png', import.meta.url).href,
  amarkantak: new URL('../assets/destinations/amarkantak.png', import.meta.url).href,
  // North-East India destinations
  cherrapunji: new URL('../assets/destinations/cherrapunji.png', import.meta.url).href,
  tawang: new URL('../assets/destinations/tawang.png', import.meta.url).href,
  zirovalley: new URL('../assets/destinations/ziro valley.png', import.meta.url).href,
  kaziranga: new URL('../assets/destinations/kaziranga.png', import.meta.url).href,
  loktalake: new URL('../assets/destinations/loktak lake.png', import.meta.url).href,
  dawki: new URL('../assets/destinations/dawki.png', import.meta.url).href,
  majuliisland: new URL('../assets/destinations/majuli island.png', import.meta.url).href,
  bomdila: new URL('../assets/destinations/bomdila.png', import.meta.url).href,
  // Gallery page images
  galleryUdaipur: new URL('../assets/images/images/gallery_udaipur.png', import.meta.url).href,
  galleryJodhpur: new URL('../assets/images/images/gallery_jodhpur.png', import.meta.url).href,
  galleryJaipur: new URL('../assets/images/images/gallery_jaipur.png', import.meta.url).href,
  galleryLucknow: new URL('../assets/images/images/gallery_lucknow.png', import.meta.url).href,
  galleryTamilnadu: new URL('../assets/images/images/gallery_tamilnadu.png', import.meta.url).href,
  galleryKonark: new URL('../assets/images/images/gallery_konark.png', import.meta.url).href,
  galleryPuri: new URL('../assets/images/images/gallery_puri.png', import.meta.url).href,
  // Additional image aliases for states
  andraPradesh: new URL('../assets/images/images/andhra pradesh.jpg', import.meta.url).href,
  chattisgarh: new URL('../assets/images/images/chattisgarh.jpg', import.meta.url).href,
  kanha: new URL('../assets/destinations/kanha national park.png', import.meta.url).href,
  delhi: new URL('../assets/images/images/delhi.jpg', import.meta.url).href,
  majuli: new URL('../assets/destinations/majuli island.png', import.meta.url).href,
  gokarna: new URL('../assets/destinations/gokarna.png', import.meta.url).href,
}

export default localImages;